### ISSUE TITLE
Repo access request

### ISSUE THREAD

**Issue by theKremmen** [STMicroelectronics/amazon-freertos-ST#2]
Requesting access to this repository as instructed in the readme.
I develop embedded solutions for customers in the industrial IoT sector, presently using STWINKT evaluation board and various nucleos as needed. The default OS is FreeRTOS so all vendor provided solutions would be welcome.

**Comment by LMESTM** [comment]
Hello 
actually the readme tells you to follow the link to send an email.
Can you please send an email as suggested ? I'll close this issue.
cheers,

**Comment by theKremmen** [comment]
Yes, but email to where?

**Comment by LMESTM** [comment]
See the link in the readme:
> an e-mail to ST using this link

The word **link** points to the email address
